services:
  plexapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}
    image: plexapp
    container_name: plexapp
    networks: [plex-network]
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - "./frontend/.env"
    depends_on:
      - plexapi
  
  plexapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: plexapi
    container_name: plexapi
    networks: [plex-network]
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - "./backend/.env"

networks:
  plex-network:
    driver: bridge