services:
  plexapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:8000
    image: plexapp
    container_name: plexapp
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - plexapi
  
  plexapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: plexapi
    container_name: plexapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - "./backend/.env"
